### ISSUE TITLE
Bug ao abrir o modal para deslogar da aplicação.

### ISSUE THREAD

**Issue by robsonmvieira** [robsonmvieira/herba-front#13]
Segue evidência a de um bug encontrado.
![ksnip_20201010-212156](https://user-images.githubusercontent.com/11168558/95667617-e010b000-0b3e-11eb-9239-3f0cd2984bd8.png)

**Comment by cleitonosilva** [comment]
corrigido

**Comment by robsonmvieira** [comment]
Você não alinhou o usuário logado com a logo da aplicação. O Mesmo está próximo do topo.

**Comment by cleitonosilva** [comment]
:lipstick: corrigido
