### ISSUE TITLE
ajuste no layout da tela de login

### ISSUE THREAD

**Issue by robsonmvieira** [robsonmvieira/herba-front#5]
### tarefas para tela de Login:

1. os inputs de login não estão sendo renderizados com as cores que consta no figma.
2. Ajustar as cores da mensgem de  erro ao tentar fazer login com email ou senha faltando
3. Ajustar o posicionamento da mensagem de erro quando inserimos o email e senha no formato correto(disse formato e não que os dados inseridos no input de fato existam no banco) bem como a cor do toast.
3. Trabalhar no estilo do toast(olha a doc do Reactstrap). Está vermelho vivo. O que pode assustar  o usuário. Pode se basear nesse link (https://i.stack.imgur.com/4bsSm.jpg)
4. Ajustar o botão pra entrar em conformidade com as demais tela. No momento o botão está pequeno

**Comment by cleitonosilva** [comment]
os inputs de login não estão sendo renderizados com as cores que consta no figma. ----  resolvido

**Comment by robsonmvieira** [comment]
Segue evidência para tratamento. Esse comportamento acontece em diversas tamanhos de  tela.

![Screen Shot 2020-10-05 at 15 46 53](https://user-images.githubusercontent.com/11168558/95119387-42724680-0722-11eb-8b2d-e474c7a8f99a.png)
@cleitonosilva

**Comment by cleitonosilva** [comment]
tela de LOGIN com suas alterações corrigidas
