### ISSUE TITLE
Lista de produtos do PDV

### ISSUE THREAD

**Issue by robsonmvieira** [robsonmvieira/herba-front#6]
**Ajustar o layout de acordo com o figma:**
1. O nome do usuário logado está na posição incorreta.
Ele deve ficar posicionado a direita conforme layout já disponibilizado no Figma.
2. Dar uma margin no botão de finalizar compra. Está colado.

**Comment by cleitonosilva** [comment]
corrigido. 

![image](https://user-images.githubusercontent.com/66958728/95209813-24a7ee80-07c1-11eb-8419-634affb6a0a4.png)
