### ISSUE TITLE
erro na Hierarquia de componentes

### ISSUE THREAD

**Issue by robsonmvieira** [robsonmvieira/herba-front#8]
@cleitonosilva, na página de help desk Há um erro lançado no Dom (document object model)

![ksnip_20201005-155537](https://user-images.githubusercontent.com/11168558/95120215-96315f80-0723-11eb-8dea-002803822a23.png)

Há algumas coisas a pontuar também nessa ela. Segue:
1. Nem tudo a vida é label.
 - o que você chama de LabelHelpDesk, na verdade deve ser BoxDescription. Esse BoxDescription não deve ser uma Tag P. Devido a hierarquia e semântica do elementos. Ele deve ser um h4 ou h5.
2. Você colocou uma tag P como container de um h5. tag P não são container de nada. Estão no final da fila de prioridades dos robos. 
3. LabelMarca não deve se chamar Label. Pode renomear apenas como Brand(Marca em inglês). Lembre-se: Devemos seguir a consistência no código. Se Já existe os componentes em inglês, misturar inglês com português é pior do que codar em português.

**Comment by cleitonosilva** [comment]
Corrigido 

![image](https://user-images.githubusercontent.com/66958728/95230232-fe417d80-07d7-11eb-9ecf-6c46959fe285.png)
